### ISSUE TITLE
dependabot complains of older version

### ISSUE THREAD

**Issue by awesomepras** [awesomepras/skills-secure-repository-supply-chain#3]
when trying to run step 2, to have dependabot fix the issue automatically, following error is displayed
`Dependabot detected the following npm requirement for your project: '6'.`

Fix options
update .github/dependabot.yml config file
```
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
```
